//! Autogenerated weights for pallet_messaging
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2024-01-01
//! 
//! These are placeholder weights. In production, run benchmarks to get accurate values.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_messaging.
pub trait WeightInfo {
	fn register_profile() -> Weight;
	fn update_profile() -> Weight;
	fn send_message_hash() -> Weight;
	fn approve_contact() -> Weight;
	fn remove_contact() -> Weight;
	fn challenge_spam() -> Weight;
	fn refund_bond() -> Weight;
}

/// Weights for pallet_messaging using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: UserProfiles (r:1 w:1)
	/// Storage: SpamBonds (r:0 w:1)
	/// Proof: Currency reserve operation
	fn register_profile() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: UserProfiles (r:1 w:1)
	fn update_profile() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: UserProfiles (r:2 w:0)
	/// Storage: SpamBonds (r:1 w:0)
	/// Storage: MessageHashes (r:0 w:1)
	/// Storage: NextMessageId (r:1 w:1)
	fn send_message_hash() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: UserProfiles (r:2 w:0)
	/// Storage: ApprovedContacts (r:1 w:1)
	/// Storage: ContactCount (r:1 w:1)
	fn approve_contact() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: ApprovedContacts (r:1 w:1)
	/// Storage: ContactCount (r:1 w:1)
	fn remove_contact() -> Weight {
		Weight::from_parts(25_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	/// Storage: MessageHashes (r:1 w:0)
	fn challenge_spam() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}

	/// Storage: SpamBonds (r:1 w:1)
	/// Proof: Currency unreserve operation
	fn refund_bond() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn register_profile() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn update_profile() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn send_message_hash() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn approve_contact() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn remove_contact() -> Weight {
		Weight::from_parts(25_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn challenge_spam() -> Weight {
		Weight::from_parts(20_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}

	fn refund_bond() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}